# Generated by Django 4.2.2 on 2023-07-04 11:32

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
