# Generated by Django 4.2.2 on 2023-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_author_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
    ]
