# Generated by Django 4.2.2 on 2023-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
