# Generated by Django 4.2.2 on 2023-07-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='static/public/cover_image/'),
            preserve_default=False,
        ),
    ]
