# Generated by Django 4.2.2 on 2023-06-27 03:38

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_blog_author_image_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
