# Generated by Django 4.2.2 on 2023-07-07 14:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_blog_image_blog_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
