# Generated by Django 4.2.2 on 2023-07-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blog_content_alter_blog_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Choose Category', 'Choose Category'), ('Technology', 'Technology'), ('Programming', 'Programming'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Finance', 'Finance')], default='Choose Category', max_length=50, null=True),
        ),
    ]
