# Generated by Django 4.2.2 on 2023-07-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
    ]
