# Generated by Django 3.2.12 on 2023-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_content_comment_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Choose Category', 'Choose Category'), ('Technology', 'Technology'), ('Programming', 'Programming'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Finance', 'Finance'), ('Other', 'Other')], default='Choose Category', max_length=50, null=True),
        ),
    ]
